/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.swing;

import com.github.britooo.looca.api.core.Looca;
import com.github.britooo.looca.api.group.memoria.Memoria;
import com.github.britooo.looca.api.group.processador.Processador;
import com.github.britooo.looca.api.group.sistema.Sistema;
import com.mycompany.swing.config.ConexaoMySQLInit;
import com.mycompany.swing.config.ConexaoSQLServer;
import com.mycompany.swing.config.ConexaoMySQL;
import com.mycompany.swing.dominio.Leitura;
import com.mycompany.swing.dominio.Notebook;
import com.mycompany.swing.dominio.Usuario;
import com.mycompany.swing.repositorio.LeituraRepositorio;
import com.mycompany.swing.repositorio.NotebookRepositorioMYSQL;
import com.mycompany.swing.repositorio.NotebookRepositorioSQLServer;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;

import static com.mycompany.swing.dominio.entidades.Alerta.insertAlerta;
import static com.mycompany.swing.dominio.entidades.Empresa.insertEmpresa;
import static com.mycompany.swing.dominio.Table.*;
import static com.mycompany.swing.dominio.entidades.Usuario.insertUsuario;

/**
 * @author victo
 */
public class app extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public app() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Senha:");

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log-in");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(51, 51, 70));
        jLabel2.setText("Usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(43, 43, 43)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                                .addComponent(jTextField1)
                                                .addComponent(jTextField2)))
                                .addContainerGap(137, Short.MAX_VALUE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(49, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String nomeDigitado = jTextField1.getText();
        String senhaDigitada = jTextField2.getText();
        System.out.println("Usuário:" + nomeDigitado);

        ConexaoSQLServer conexaoSQLServer = new ConexaoSQLServer();
        JdbcTemplate con = conexaoSQLServer.getConexaoDoBanco();

        System.out.println("Conexão com bando de dados SQL Server efetuada com sucesso!");

        ConexaoMySQLInit conexaoMySQLInit = new ConexaoMySQLInit();
        Connection connInit = conexaoMySQLInit.getJdbcTemplateMySQL();

        try {
            Statement statement = connInit.createStatement();

            String[] sqlCommands = {
                    "CREATE DATABASE IF NOT EXISTS monitoramento",
                    "USE monitoramento",
                    "CREATE TABLE IF NOT EXISTS empresa ("
                            + "idEmpresa INT PRIMARY KEY AUTO_INCREMENT,"
                            + "nomeFantasia VARCHAR(45),"
                            + "cnpj CHAR(15),"
                            + "emailResponsavel VARCHAR(35),"
                            + "telefone VARCHAR(45)"
                            + ")",

                    "CREATE TABLE IF NOT EXISTS usuario ("
                            + "idUsuario INT AUTO_INCREMENT,"
                            + "nome VARCHAR(45),"
                            + "email VARCHAR(35),"
                            + "senha VARCHAR(45),"
                            + "tipo VARCHAR(45),"
                            + "CHECK (tipo IN ('root','supervisor','suporte', 'atendente')),"
                            + "fkEmpresa INT,"
                            + "FOREIGN KEY (fkEmpresa) REFERENCES empresa (idEmpresa),"
                            + "PRIMARY KEY(idUsuario, fkEmpresa)"
                            + ")",

                    "CREATE TABLE IF NOT EXISTS alerta ("
                            + "idAlerta INT PRIMARY KEY AUTO_INCREMENT,"
                            + "minCpu DECIMAL(10,2),"
                            + "maxCpu DECIMAL(10,2),"
                            + "minMemoria DECIMAL(10,2),"
                            + "maxMemoria DECIMAL(10,2),"
                            + "fkEmpresa INT,"
                            + "FOREIGN KEY (fkEmpresa) REFERENCES empresa (idEmpresa)"
                            + ")",

                    "CREATE TABLE IF NOT EXISTS notebook ("
                            + "idNotebook INT PRIMARY KEY AUTO_INCREMENT,"
                            + "marca VARCHAR(45),"
                            + "modelo VARCHAR(45),"
                            + "capacidadeRam VARCHAR(45),"
                            + "velocidadeCpu VARCHAR(45),"
                            + "ipNotebook VARCHAR(45),"
                            + "fkUsuario INT,"
                            + "fkEmpresa INT,"
                            + "FOREIGN KEY (fkUsuario) REFERENCES usuario (idUsuario),"
                            + "FOREIGN KEY (fkEmpresa) REFERENCES empresa (idEmpresa)"
                            + ")",

                    "CREATE TABLE IF NOT EXISTS dadosCapturados ("
                            + "idDadosCapturados INT PRIMARY KEY AUTO_INCREMENT,"
                            + "porcentagemUsoMemoria INT,"
                            + "porcentagemUsoProcessador INT,"
                            + "dataHora DATETIME DEFAULT CURRENT_TIMESTAMP,"
                            + "fkNotebook INT,"
                            + "FOREIGN KEY (fkNotebook) REFERENCES notebook (idNotebook),"
                            + "fkUsuario INT,"
                            + "fkEmpresa INT,"
                            + "FOREIGN KEY (fkUsuario) REFERENCES usuario (idUsuario),"
                            + "FOREIGN KEY (fkEmpresa) REFERENCES empresa (idEmpresa)"
                            + ")"
            };

            for (String sqlCommand : sqlCommands) {
                statement.executeUpdate(sqlCommand);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    jLabel6.setVisible(true);
                    jLabel6.setText("Erro na pausa de thread.");
                }
            }

            if (isTableEmpty(connInit, "empresa")) {
                insertEmpresa(connInit, "Acflazz", "123456789012365", "acflazz@gmail.com", "11974748563");
                insertEmpresa(connInit, "Juliana", "123456789123456", "juliana@gmail.com", "11355447789");
                insertEmpresa(connInit, "ICE", "123456789123456", "ice@gmail.com", "11234567897");
                insertEmpresa(connInit, "Gesso", "08338976000180", "erick.tricolor9@gmail.com", "11951534515");
                insertEmpresa(connInit, "Apple", "30381362000130", "erick.tricolor9@gmail.com", "11951534515");
            }

            if (isTableEmpty(connInit, "usuario")) {
                insertUsuario(connInit, "Erick", "erick@gmail.com", "Acessar@", "root", 1);
                insertUsuario(connInit, "Juliana", "juliana@gmail.com", "Acessar@", "root", 2);
                insertUsuario(connInit, "Pytel", "pytel@gmail.com", "Acessar@", "suporte", 2);
                insertUsuario(connInit, "Matheus", "matheus@gmail.com", "Acessar@", "atendente", 2);
                insertUsuario(connInit, "Leonardo", "leo@gmail.com", "Acessar@", "root", 3);
                insertUsuario(connInit, "Nathalia", "nathalia.obi@gmail.com", "Acessar@", "root", 5);
            }

            if (isTableEmpty(connInit, "alerta")) {
                insertAlerta(connInit, 20.0, 80.0, 20.0, 80.0, 1);
                insertAlerta(connInit, 15.0, 75.0, 15.0, 75.0, 2);
                insertAlerta(connInit, 25.0, 85.0, 25.0, 85.0, 3);
                insertAlerta(connInit, 18.0, 78.0, 18.0, 78.0, 4);
                insertAlerta(connInit, 22.0, 82.0, 22.0, 82.0, 5);
            }

            ConexaoMySQL conexaoMySQL = new ConexaoMySQL();
            Connection conn = conexaoMySQL.getJdbcTemplateMySQL();

            LeituraRepositorio leituraRepositorio = new LeituraRepositorio(con, conn);
            NotebookRepositorioMYSQL notebookRepositorioMYSQL = new NotebookRepositorioMYSQL(conn);
            NotebookRepositorioSQLServer notebookRepositorioSQLServer = new NotebookRepositorioSQLServer(con);

            Looca looca = new Looca();
            Sistema sistema = looca.getSistema();
            String marca = sistema.getFabricante();
            String modelo = sistema.getSistemaOperacional();

            Processador processador = looca.getProcessador();
            String velocidadeCpu = processador.getFrequencia().toString();

            String capacidadeRam = looca.getMemoria().getTotal().toString();

            try {
                Usuario listaUsuario = con.queryForObject("SELECT * FROM usuario WHERE nome = ? AND senha = ?",
                        new BeanPropertyRowMapper<>(Usuario.class), nomeDigitado, senhaDigitada);

                Stream.of(jTextField1, jTextField2, jButton1, jLabel1, jLabel2, jLabel3)
                        .forEach(componente -> componente.setVisible(false));

                jLabel6.setVisible(true);
                jLabel6.setText("Usuário logado! Capturando dados...");
                System.out.println("Usuário logado!");

                assert listaUsuario != null;
                int idUsuario = listaUsuario.getIdUsuario();

                String selectEmpresa = "SELECT fkEmpresa FROM usuario WHERE idUsuario = ?";
                Map<String, Object> empresaMap = con.queryForMap(selectEmpresa, listaUsuario.getIdUsuario());
                int foreignEmpresa = (int) empresaMap.get("fkEmpresa");

                if (notebookExistsForUserSqlServer(con, idUsuario)) {
                    System.out.println("Ja existe um notebook para esse usuario!");
                } else {
                    Notebook notebook = new Notebook(marca, modelo, capacidadeRam, velocidadeCpu, null, idUsuario, foreignEmpresa);
                    notebookRepositorioSQLServer.inserir(notebook);
                    System.out.println("Notebook inserido no SQL Server:" + notebook);

                }

                if (notebookExistsForUser(conn, idUsuario)) {
                    System.out.println("Ja existe um notebook para esse usuario!");
                } else {
                    Notebook notebook = new Notebook(marca, modelo, capacidadeRam, velocidadeCpu, null, idUsuario, foreignEmpresa);
                    try {
                        notebookRepositorioMYSQL.inserir(notebook);
                        System.out.println("Notebook inserido no MYSQL:" + notebook);
                    } catch (Exception e) {
                        System.out.println("Erro ao inserir notebook no MySQL");
                    }
                }

                String selectNotebook = "SELECT idNotebook, fkEmpresa FROM notebook WHERE fkUsuario = ?";
                Map<String, Object> notebookMap = con.queryForMap(selectNotebook, listaUsuario.getIdUsuario());
                int fkEmpresa = (int) notebookMap.get("fkEmpresa");
                int idNotebook = (int) notebookMap.get("idNotebook");

                new Timer().scheduleAtFixedRate(new TimerTask() {
                    final Looca looca = new Looca();
                    final Memoria memoria = looca.getMemoria();
                    final Processador processador = looca.getProcessador();

                    @Override
                    public void run() {
                        try {
                            System.out.println("Dados Capturados:");
                            int percentualMemoria = (int) ((memoria.getEmUso() * 100) / memoria.getTotal() * 0.50);
                            System.out.println("Percentual de Memoria:" + percentualMemoria + "%");

                            double percentualUso = processador.getUso() * 100;
                            int percentualCPU = (int) Math.round(percentualUso * 0.50);
                            int percentualCPUWithMin = Math.min(percentualCPU, 100);
                            System.out.println("Percentual de CPU:" + percentualCPUWithMin + "%");

                            LocalDateTime dataHoraConsulta = LocalDateTime.now();
                            System.out.println("Data e Hora da Consulta:" + dataHoraConsulta);
                            System.out.println("--------------");

                            Leitura leitura = new Leitura(
                                    percentualMemoria,
                                    percentualCPUWithMin,
                                    dataHoraConsulta,
                                    idNotebook,
                                    listaUsuario.getIdUsuario(),
                                    fkEmpresa
                            );

                            leituraRepositorio.inserir(leitura);

                        } catch (Exception e) {
                            Logger.getLogger(getClass().getName()).log(Level.SEVERE, "Erro ao capturar dados", e);
                        }
                    }
                }, 0, 10000);
            } catch (EmptyResultDataAccessException e) {
                jLabel6.setVisible(true);
                jLabel6.setText("Usuário ou senha incorretos.");
            }
        } catch (SQLException e) {
            jLabel6.setVisible(true);
            jLabel6.setText("Erro durante a execução!.");
            throw new RuntimeException(e);
        }
    } //GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new app().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
